# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5 # <%= ENV['DEMO_ADISON_PUBLISHER_POOL'] || 5 %>
  database: demo_adison_publisher
  username: root # <%= ENV['DEMO_ADISON_PUBLISHER_USER'] %>
  password: qwerqwer! # <%= ENV['DEMO_ADISON_PUBLISHER_PASSWORD'] %>
  host: 127.0.0.1 # <%= ENV['DEMO_ADISON_PUBLISHER_HOST'] %>
  port: 3310 # <%= ENV['DEMO_ADISON_PUBLISHER_PORT'] %>
  socket: /tmp/mysql.sock
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
